#!/bin/sh
while ! pg_isready; do sleep 1; done
DATA_SOURCE_NAME="postgresql://supabase_admin@localhost:5432/postgres?sslmode=disable" \
/usr/sbin/postgres_exporter 2>&1 | tee /tmp/service-pgexporter.fifo
