#!/bin/sh
while ! pg_isready; do sleep 1; done
# Note: PGBOUNCER_EXPORTER_CONNECTION_STRING needs to be set in environment
# Format: "postgres://user:password@localhost:6432/pgbouncer?sslmode=disable"
/usr/sbin/pgbouncer_exporter 2>&1 | tee /tmp/service-pgbouncer-exporter.fifo
