#!/bin/sh
while ! test -f /var/run/postgresql/.migration.done; do sleep 1; done

CONFIG_FILE="/tmp/pgbouncer.ini"
cp /vela/config/pgbouncer_pg18.ini "$CONFIG_FILE"

sed -i 's/client_tls_sslmode = require/client_tls_sslmode = disable/g' "$CONFIG_FILE"

log() {
    printf '%s %s\n' "$(date '+%Y-%m-%dT%H:%M:%S%z')" "$*"
}

setup_tls_hot_reload() {
    (
        log "Waiting for certificates..."
        while ! test -s /vela/certs/tls.key || ! test -s /vela/certs/tls.crt; do sleep 5; done
        
        log "Certificates found. Enabling TLS and reloading PgBouncer..."
        sed -i 's/client_tls_sslmode = disable/client_tls_sslmode = require/g' "$CONFIG_FILE"
        killall -HUP pgbouncer

        while true; do
            inotifywait -e modify,create,delete,move /vela/certs > /dev/null 2>&1
            log "Certificates modified, reloading PgBouncer..."
            killall -HUP pgbouncer
            sleep 2
        done
    ) &
}

setup_tls_hot_reload

/usr/sbin/pgbouncer "$CONFIG_FILE" 2>&1 | tee /tmp/service-pgbouncer.fifo
