#!/bin/sh

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - pgbouncer-server: $@"
}

while ! test -f /var/run/postgresql/.migration.done; do sleep 1; done

setup_tls_hot_reload() {
    log "Waiting for certificates..."
    while ! test -f /vela/certs/tls.key || ! test -f /vela/certs/tls.crt; do sleep 1; done
    log "Certificates found. Starting hot-reload watcher in background..."

    (
      while true; do
          inotifywait -e modify,create,delete,move /vela/certs > /dev/null 2>&1
          log "Certificates modified, reloading PgBouncer..."
          killall -HUP pgbouncer
          sleep 2
      done
    ) &
}

setup_tls_hot_reload

/usr/sbin/pgbouncer /vela/config/pgbouncer_pg18.ini 2>&1 | tee /tmp/service-pgbouncer.fifo
