#!/bin/sh
set -eu

is_fd_open() {
  # returns 0 if open, 1 if closed
  [ -e "/proc/$$/fd/$1" ]
}

find_free_fd() {
  start="${1:-3}"
  fd="$start"
  while [ "$fd" -lt 1024 ]; do
    if ! is_fd_open "$fd"; then
      echo "$fd"
      return 0
    fi
    fd=$((fd+1))
  done
  return 1
}

load_fifo_to_fd() {
  fifo="$1"
  variable="$2"
  fd=$(find_free_fd 10)
  eval "exec $fd<>\"$fifo\""
  eval "export $variable=$fd"
}

load_fifo_to_fd "/tmp/service-postgrest.fifo" "VEC_SRV_POSTGREST_FD"
load_fifo_to_fd "/tmp/service-storage.fifo" "VEC_SRV_STORAGE_FD"
load_fifo_to_fd "/tmp/service-pgmeta.fifo" "VEC_SRV_PGMETA_FD"
load_fifo_to_fd "/tmp/service-pgexporter.fifo" "VEC_SRV_PGEXPORTER_FD"
load_fifo_to_fd "/tmp/service-pgbouncer.fifo" "VEC_SRV_PGBOUNCER_FD"
load_fifo_to_fd "/tmp/service-postgresql.fifo" "VEC_SRV_POSTGRESQL_FD"

export VELA_BRANCH="$(cat /vela/secrets/analytics/branch | awk '{print toupper($0)}')"

/sbin/vector -c /etc/vector/vector.yaml --color never
