PGROUTING_VERSION = 4.0.0
PGROUTING_SOURCE = v$(PGROUTING_VERSION).tar.gz
PGROUTING_SITE = https://github.com/pgRouting/pgrouting/archive
PGROUTING_LICENSE = PostgreSQL
PGROUTING_LDFLAGS = $(TARGET_LDFLAGS) $(TARGET_NLS_LIBS)
PGROUTING_DEPENDENCIES = postgresql boost
PGROUTING_SUPPORTS_IN_SOURCE_BUILD = NO

$(eval $(cmake-package))