#!/bin/sh
cd /opt/meta
while ! pg_isready; do sleep 1; done
PG_META_PORT="8080" \
PG_META_DB_HOST="localhost" \
PG_META_DB_PORT="5432" \
PG_META_DB_NAME="postgres" \
PG_META_DB_USER="supabase_admin" \
PG_META_DB_PASSWORD="$(cat /vela/secrets/db/password)" \
PG_META_DB_DRIVER="postgres" \
PG_META_DB_SSL_MODE="disable" \
PG_META_DB_URL="" \
CRYPTO_KEY="$(cat /vela/secrets/db/pgmeta_crypto_key)" \
/usr/bin/node dist/server/server.js 2>&1 | tee /tmp/service-pgmeta.fifo
