#!/bin/bash

source ./scripts/setup-env

git config --global credential.helper store
echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials

function expandBuildrootVariables() {
  make -f - expand -- "${@}" <<'EOF'
args := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
expanded := $(eval expanded := $(args))$(expanded)
.RECIPEPREFIX := >
.PHONY: expand
expand:
>@printf '%s' $(expanded)
%:
>@:
EOF
}

function getBusyboxConfigPath() {
  bbconf="$(cat "$1" | grep BR2_PACKAGE_BUSYBOX_CONFIG= | sed 's/BR2_PACKAGE_BUSYBOX_CONFIG="\(.*\)"/\1/')"
  echo "$(expandBuildrootVariables "${bbconf}")"
}

function setupBuildroot() {
  board=${1:-`echo vela-qemu-x64`}
  case "${board}" in
    vela-qemu-x64 )
      defconfig="vela_qemu_x64_defconfig"
    ;;

    * )
      defconfig="${board}_defconfig"
    ;;
  esac

  if [ ! -f ${PATH_PROTOTYPE}/configs/${defconfig} ] && [ ! -f ${PATH_BUILDROOT}/configs/${defconfig} ]; then
    echo "Unknown board configuration set '${defconfig}'"
    exit 1
  fi

  echo "Setting up buildroot to use configuration '${defconfig}'"
  make O=${BR2_OUTPUT_PATH} ${defconfig}

  if [ -f ${PATH_OUTPUT}/.config ]; then
    echo "Creating builder configuration..."
    echo "${PATH_DEVKIT}/builder.conf"
    [ -f "${PATH_DEVKIT}/builder.conf" ] && rm -rf "${PATH_DEVKIT}/builder.conf"
    echo "volDownloadCache=\"${volDownloadCache}\"" > "${PATH_DEVKIT}/builder.conf"
    echo "volCompilerCache=\"${volCompilerCache}\"" >> "${PATH_DEVKIT}/builder.conf"
    if [ -f ${PATH_PROTOTYPE}/configs/${defconfig} ]; then
      echo "buildrootDefconfig=\"${PATH_PROTOTYPE}/configs/${defconfig}\"" >> "${PATH_DEVKIT}/builder.conf"
    elif [ -f ${PATH_BUILDROOT}/configs/${defconfig} ]; then
      echo "buildrootDefconfig=\"${PATH_BUILDROOT}/configs/${defconfig}\"" >> "${PATH_DEVKIT}/builder.conf"
    fi
    busyboxConfig="$(getBusyboxConfigPath "${PATH_OUTPUT}/.config")"
    echo "busyboxDefconfig=\"${busyboxConfig}\"" >> "${PATH_DEVKIT}/builder.conf"
  fi
}

cd ${PATH_BUILDROOT}
MAKE="make O= O=${BR2_OUTPUT_PATH}"

echo "Loading buildroot..."

export SDK_NAME="x86_64-buildroot-linux-gnu_sdk-buildroot-host-${OS,,}-${ARCH}"

args=( "$@" )
case "${1}" in
  setup )
    setupBuildroot "${args[@]:1}"
  ;;

  config )
    export TERM=xterm
    tool=${2:-`echo buildroot`}
    case "${tool}" in
      linux )
        ${MAKE} linux-nconfig
      ;;

      busybox )
        ${MAKE} O=${BR2_OUTPUT_PATH} busybox-menuconfig
      ;;

      barebox )
        ${MAKE} O=${BR2_OUTPUT_PATH} barebox-menuconfig
      ;;

      * )
        ${MAKE} O=${BR2_OUTPUT_PATH} nconfig
      ;;
    esac
  ;;

  saveconfig )
    if [ ! -d ${BR2_OUTPUT_PATH}/build ]; then
      echo "Working directory not yet setup, please run 'builder setup'"
      exit -1
    fi

    echo "Saving buildroot configuration..."
    ${MAKE} savedefconfig

    if ls ${BR2_OUTPUT_PATH}/build/busybox-* 1> /dev/null 2>&1; then
      echo "Saving Busybox configuration..."
      bbconf="$(getBusyboxConfigPath "${buildrootDefconfig}")"
      cp "${bbconf}" "${bbconf}.old"
      ${MAKE} busybox-update-config
      [ "$(diff -u "${bbconf}" "${bbconf}.old" | grep -c "@@")" = "1" ] && \
          echo "Busybox config unchanged, reverting..." && \
          rm "${bbconf}" && \
          mv "${bbconf}.old" "${bbconf}"
      [ -f "${bbconf}.old" ] && rm "${bbconf}.old"
    fi

    if ls ${BR2_OUTPUT_PATH}/build/barebox-* 1> /dev/null 2>&1; then
      echo "Saving Barebox configuration..."
      ${MAKE} barebox-update-defconfig
    fi

    if ls ${BR2_OUTPUT_PATH}/build/linux-* 1> /dev/null 2>&1; then
      echo "Saving Linux configuration..."
      ${MAKE} linux-update-defconfig
    fi
  ;;

  clean )
    case "${2}" in
      target )
        echo "Cleaning target directory..."
        rm -rf ${BR2_OUTPUT_PATH}/target
        find ${BR2_OUTPUT_PATH}/ -name ".stamp_target_installed" | xargs rm -rf
      ;;

      ccache )
        echo "Cleaning CCACHE directory..."
        rm -rf ${HOME}/ccache/*
      ;;

      dlcache )
        echo "Cleaning download directory..."
        rm -rf ${HOME}/dlcache/*
      ;;

      * )
        if [ "${2}" != "" ]; then
          echo "Cleaning package ${2}..."
          if [ "$(${MAKE} ${2}-show-depends > /dev/null 2>&1 && echo $?)" == "0" ]; then
            ${MAKE} ${2}-dirclean
          fi
        else
          echo "Cleaning everything..."
          ${MAKE} clean
        fi
      ;;
    esac
  ;;

  build )
    echo "Running multithreaded build with ${BR2_JLEVEL} make instances"
    if [ "${2}" == "dts" ]; then
       ${MAKE} linux-rebuild
    elif [ ! "${2}" == "" ]; then
      ${MAKE} ${2}-build
    else
      ${MAKE}
    fi
  ;;

  rebuild )
    ${MAKE} ${2}-rebuild
  ;;

  download )
    ${MAKE} source
  ;;

  dependencies )
    BR2_GRAPH_OUT=svg ${MAKE} graph-depends
    cp ${BR2_OUTPUT_PATH}/graphs/graph-depends.* ${BR2_OUTPUT_PATH}/images/
  ;;

  buildtimegraph )
    ${MAKE} graph-build
    cp ${BR2_OUTPUT_PATH}/graphs/build.* ${BR2_OUTPUT_PATH}/images/
  ;;

  buildsize )
    ${MAKE} graph-size
    cp ${BR2_OUTPUT_PATH}/graphs/graph-size.pdf ${BR2_OUTPUT_PATH}/images/
    cp ${BR2_OUTPUT_PATH}/graphs/package-size-stats.csv ${BR2_OUTPUT_PATH}/images/
    cp ${BR2_OUTPUT_PATH}/graphs/file-size-stats.csv ${BR2_OUTPUT_PATH}/images/
  ;;

  licenses )
    ${MAKE} legal-info
  ;;

  makesdk )
    ${MAKE} sdk
    mv ${BR2_OUTPUT_PATH}/images/x86_64-buildroot-linux-gnu_sdk-buildroot.tar.gz ${BR2_OUTPUT_PATH}/images/x86_64-buildroot-linux-gnu_sdk-buildroot-host-${OS,,}-${ARCH}.tar.gz
  ;;

  env )
    ${MAKE} -s printvars
  ;;

  * )
    echo "Unknown command"
    exit 1
  ;;
esac