#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Script cannot run on its own, please use the builder script to build the VelaOS"
  exit 1
fi

function dockerVolumeExists() {
    ${DOCKER} volume inspect $1 1> /dev/null 2>&1
    [ "$?" == "1" ] && echo 1 || echo 0
}

function ensureVolume() {
    [ "$(dockerVolumeExists $1)" == "1" ] && echo -n "Creating volume " && ${DOCKER} volume create --name $1
}

function removeVolume() {
    [ "$(dockerVolumeExists $1)" == "0" ] && echo -n "Destroying volume " && ${DOCKER} volume rm -f $1
}

function cleanVolumes() {
    for vol in ${internalVolumes[@]}; do
        removeVolume $vol
    done
}

function makeVolumes() {
    for vol in ${internalVolumes[@]}; do
        ensureVolume $vol
    done
}

function rebuildVolumes() {
    cleanVolumes
    makeVolumes
}

args=( "$@" )
case "${args[0]}" in
    setup )
        if containerImageExists; then
            if [ "${args[1]}" == "-i" ]; then
                echo "Container image already exists. Skipping build."
                exit 0
            fi
        fi
        if containerImageOutOfDate; then
            echo "An older container image already exists. A new version will be built but the old one will still be in the cache. Consider cleaning it."
        fi
        cat ${BASEDIR}/scripts/Dockerfile | ${DOCKER} build -t ${containerImageName} - || exit 1
        makeVolumes
    ;;

    purge )
        if containerImageExists; then
            ${DOCKER} image rm -f ${containerImageName}
            cleanVolumes
        fi
    ;;

    clean )
        if containerImageExists; then
            rebuildVolumes
        fi
    ;;

    rm )
        if containerImageExists; then
            cleanVolumes
        fi
    ;;

    shell )
        ${DOCKER} run --rm --name ${containerName}-task \
            -it -w /opt/builder ${dockerVolumes} \
            ${containerImageName} \
            /bin/bash
    ;;

    store )
        ${DOCKER} container commit ${containerImageName}
    ;;

    reclaim )
        for image in $(${DOCKER} image list 2>&1 | grep ${containerName}); do
            ${DOCKER} image ${image}
        done
    ;;

    rebuild )
        if containerImageExists; then
            ${DOCKER} image rm ${containerImageName}
        fi
        cat ${BASEDIR}/scripts/Dockerfile | ${DOCKER} build -t ${containerImageName} - || exit 1
    ;;

    * )
        echo "Unknown command"
        exit 1
    ;;
esac
