#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Setup script cannot run on its own, please use the builder script to build the VelaOS"
  exit 1
fi

function insideContainer() {
  [ -f /proc/self/cgroup ] && grep 'docker\|lxc' /proc/self/cgroup
  echo $?
}

function detectARCH() {
  uname="$(uname -m)"
  case ${uname} in
    x86_64|amd64 )
      if [ "$(getconf LONG_BIT)" == "64" ]; then
        echo "amd64"
      else
        echo "x86"
      fi
    ;;

    i?86|x86 )
      echo "x86"
    ;;
  esac
}

function detectWSL() {
  uname="$(uname -a)"
  test ${IS_LINUX} && version="$(cat /proc/version)"
  test ${IS_LINUX} && release="$(cat /proc/sys/kernel/osrelease)"

  [[ "${uname}" == *"Microsoft"* ]] || [[ "${uname}" == *"WSL"* ]] || \
  [[ "${version}" == *"Microsoft"* ]] || [[ "${version}" == *"WSL"* ]] || \
  [[ "${release}" == *"Microsoft"* ]] || [[ "${release}" == *"WSL"* ]] && echo "0" && exit 0
  echo "1" && exit 1
}

function detectWSL2() {
  uname="$(uname -a)"
  [[ "${uname}" == *"microsoft-standard"* ]] && echo "0" && exit 0
  echo "1" && exit 1
}

function detectOS() {
  os="$(uname)"
  case $os in
    Linux )
      echo "Linux"
    ;;

    WindowsNT )
      echo "Windows"
    ;;

    Darwin )
      echo "OSX"
    ;;

    * )
      echo "Unsupported OS" >&2
      exit 1
    ;;
  esac
}

function executable() {
  local ret="$(command -v ${1})"
  if ! [ -x "$ret" ]; then
    echo "Error: executable ${1} not found." 1>&2
    exit 1
  fi
  echo "$ret"
  exit 0
}


if [ "${JOB_NAME}" != "" ]; then
  echo "Detected Jenkins builder, running non-interactive"
  AUTOBUILD_MODE=true
fi

export TERM=screen-256color
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

export ARCH=$(detectARCH)
export OS=$(detectOS)

[ "${OS}" == "Linux" ] && export IS_LINUX=true
[ "${OS}" == "OSX" ] && export IS_OSX=true
[ "${OS}" == "Windows" ] || [ "$(detectWSL)" == "0" ] && export IS_WINDOWS=true
test ${IS_WINDOWS} && [ "$(detectWSL)" == "0" ] && export IS_WSL=true
test ${IS_LINUX} && [ "$(detectWSL2)" == "0" ] && export IS_WSL2=true

# Executables
if [[ $(insideContainer) == 1 ]]; then
  echo "Checking necessary executables..."
  export DOCKER="$(executable docker)"
  test $? == 0 || exit 1
  echo "docker: ${DOCKER}"

  export GIT="$(executable git)"
  test $? == 0 || exit 1
  echo "git: ${GIT}"

  export AWK="$(executable awk)"
  test $? == 0 || exit 1
  echo "awk: ${AWK}"

  export SED="$(executable sed)"
  test $? == 0 || exit 1
  echo "sed: ${SED}"
fi

# Basic container name
containerName=${CONTAINERNAME:-vela-os-builder}

# Directories
PATH_DEVKIT="/opt/builder"
PATH_BUILDROOT="${PATH_DEVKIT}/buildroot"
PATH_OUTPUT="${PATH_DEVKIT}/output"
PATH_DL_CACHE="${PATH_DEVKIT}/dlcache"
PATH_IMAGES="${PATH_OUTPUT}/images"
PATH_SCRIPTS="${PATH_DEVKIT}/scripts"
PATH_PROTOTYPE="${PATH_DEVKIT}/prototype"
PATH_CCACHE="${PATH_DEVKIT}/ccache"

# Volumes
volDevkit="${containerName}-velaos"
volDownloadCache="${containerName}-dlcache"
volOutput="${containerName}-output"

internalVolumes=($volDownloadCache $volOutput $volDevkit)

if [ "EXT_DL_CACHE" != "" ]; then
  volDownloadCache="${EXT_DL_CACHE}"
fi

# Docker Volume Mounts
dockerVolumes=" --volume=${volDevkit}:${PATH_DEVKIT} \
		--volume=${BASEDIR}/scripts:${PATH_SCRIPTS} \
		--volume=${BASEDIR}/prototype:${PATH_PROTOTYPE} \
		--volume=${BASEDIR}/buildroot:${PATH_BUILDROOT} \
                --volume=${volDownloadCache}:${PATH_DL_CACHE} \
		--volume=${volOutput}:${PATH_OUTPUT} \
                --volume=${BASEDIR}/images:${PATH_IMAGES} \
                --volume=${HOME}/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
                --volume=${HOME}/.vault-token:/root/.vault-token \
"

# Adding CCACHE features
if [ ${AUTOBUILD_MODE} ]; then
    dockerVolumes+="--volume=${HOME}/ccache:${PATH_CCACHE}"
    export BR2_CCACHE="y"
    export BR2_CCACHE_DIR="${PATH_CCACHE}"
fi

export BR2_EXTERNAL="${PATH_PROTOTYPE}"
export BR2_EXTERNAL_COMMON_ROOTFS="${BR2_EXTERNAL}/board/vela/common/rootfs_overlay"
export BR2_EXTERNAL_CONFIGS="${BR2_EXTERNAL}/configs"
export BR2_PACKAGE_BUSYBOX_CONFIG="${BR2_EXTERNAL}/board/vela/common/"

export BUILDROOT_PATH="${PATH_BUILDROOT}"
export BR2_OUTPUT_PATH="${PATH_OUTPUT}"
export BR2_DLCACHE_PATH="${PATH_DL_CACHE}"

