#!/bin/bash

if [[ "${VELAOS_VERSION}" != "" ]] && [[ "${VELAOS_BUILD}" != "" ]]; then
  echo "Version information already set, skipping..."
  return
fi

if [[ "${SED}" == "" ]]; then
  dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source ${dir}/setup-env
fi

highestMajor=0
highestMinor=0
highestBuild=0

gitBranch=${GIT_BRANCH##origin/}
if [ "${gitBranch}" == "" ]; then
  unset gitBranch
fi

gitrev=$(${GIT} describe --long --dirty --tags)
branch=${gitBranch:-$(git rev-parse --abbrev-ref HEAD)}
distance=$(echo ${gitrev} | ${AWK} -F "-" '{printf("%s-%s", $3, $2)}')
dev=$((test "$(echo ${gitrev} | ${AWK} -F"-" '{print $4}')" == "dirty" || test "${branch}" != "master")  && echo "-dev")
buildDate=$(date +'%Y%m%d%H%M%S')
ref=$(${GIT} log --pretty=format:'%h' -n 1)

for tag in $(${GIT} tag -l | grep 'v' | ${SED} 's/v//g')
do
  numbers=($(echo ${tag} | ${AWK} -F "." '{print $1, $2, $3}'))
  major=${numbers[0]}
  minor=${numbers[1]}
  build=${numbers[2]}

  if [ ${major} -gt ${highestMajor} ]; then
    highestMajor=${major}
    highestMinor=0
    highestBuild=0
  fi

  if [ ${minor} -gt ${highestMinor} ]; then
    highestMinor=${minor}
  fi

  if [ ${build} -gt ${highestBuild} ]; then
    highestBuild=${build}
  fi
done

if [ ${NEXT_MAJOR} ]; then
  highestMajor=$((${highestMajor} + 1))
  highestMinor=0
  highestBuild=0
elif [ ${NEXT_MINOR} ]; then
  highestMinor=$((${highestMinor} + 1))
  highestBuild=0
else
  highestBuild=$((${highestBuild} + 1))
fi

export VELAOS_VERSION_MAJOR=${highestMajor}
export VELAOS_VERSION_MINOR=${highestMinor}
export VELAOS_VERSION_BUILD=${highestBuild}
export VELAOS_BUILD_DATE=${buildDate}
export VELAOS_BUILD_REF=${ref}
export VELAOS_BUILD_DEV=${dev}

export VELAOS_VERSION="${highestMajor}.${highestMinor}.${highestBuild}${dev}"
export VELAOS_BUILD="${buildDate}-${branch}-${distance}-${ref}"

if [ "${JOB_NAME}" != "" ]; then
  echo -n "Writing build.properties... "
  echo "VELAOS_VERSION_MAJOR=${VELAOS_VERSION_MAJOR}" > build.properties
  echo "VELAOS_VERSION_MINOR=${VELAOS_VERSION_MINOR}" >> build.properties
  echo "VELAOS_VERSION_BUILD=${VELAOS_VERSION_BUILD}" >> build.properties
  echo "VELAOS_BUILD_DATE=${VELAOS_BUILD_DATE}" >> build.properties
  echo "VELAOS_BUILD_REF=${VELAOS_BUILD_REF}" >> build.properties
  echo "VELAOS_BUILD_DEV=${VELAOS_BUILD_DEV}" >> build.properties
  echo "VELAOS_VERSION=${VELAOS_VERSION}" >> build.properties
  echo "VELAOS_BUILD=${VELAOS_BUILD}" >> build.properties
  echo "done."
fi

echo "Next Version: ${VELAOS_VERSION}"
echo "Build: ${VELAOS_BUILD}"
